### ISSUE TITLE
Crashing With Creative Tab.

### ISSUE THREAD

**Issue by KXIIIS** [DoubleNegation/CompactOres#10]
Whenever I try to click on the creative tab for compact ores, the game crashes. 
[crash-2020-04-12_17.00.46-client.txt](https://github.com/DoubleNegation/CompactOres/files/4467225/crash-2020-04-12_17.00.46-client.txt)

**Comment by DoubleNegation** [comment]
The tooltip that is added by Project MMO was causing the crash because it didn't supply a block state to the getBlockHardness method. Instead of crashing when there is no block state, compact ores now returns the hardness of stone. This does however mean that the tooltip is not accurate.

**Comment by KXIIIS** [comment]
Thank you so much for the update.
