### ISSUE TITLE
Crash w/ Create's Compact Copper Ore

### ISSUE THREAD

**Issue by WenXin20** [DoubleNegation/CompactOres#13]
`Minecraft v1.15.2`
`Forge v31.2.5`
`Compact Ores v2.1.2`
[`Create v0.2.4a`](https://www.curseforge.com/minecraft/mc-mods/create)

Create adds Copper Ore which has a blockstate called Oxidation, but after adding this ore to allow for compact ore generation, the game crashes when loading the world because of this blockstate.
[Crash Report](https://gist.github.com/WenXin20/272cd9c06e378eeeefd1e0279573ed33)

**Comment by DoubleNegation** [comment]
Sorry for ignoring this issue for two weeks, I was hoping that I could find a proper solution for this, but unfortunately it doesn't seem like it.  
It shouldn't be too difficult to fix the crash itself. I'll probably push a fix for it soon-ish and include it in the (probably) final 1.15 update before I move on to 1.16.  
However, properly supporting the oxidation behavior would mean that compact ores would have to pretend to be an entirely different block. This *could* be possible in theory, but if there is a solution that works, it would be super hacky and probably cause more problems than it solves. So unfortunately, properly supporting the Create oxidation functionality is not reasonably doable.  
The fix that I'll implement will simply emulate the compact ore to be the default state of the actual ore in some places where shouldn't break anything.

**Comment by WenXin20** [comment]
Thanks! If the crash is fixed, then I don't mind if the oxidation doesn't work properly. :)
