### ISSUE TITLE
Support for Deextinction Ores

### ISSUE THREAD

**Issue by WenXin20** [DoubleNegation/CompactOres#14]
I'm not sure if this is possible to support, but the mod [Deextinction](https://www.curseforge.com/minecraft/mc-mods/de-extinction-mod)  currently adds an ore called the Fossil Block. 
It has to be mined with a Rock Pick to drop anything, which, once broken, becomes a 3D block with different facing states and with the if `deextinction:block_fossil_broken`, then it has to be mined again, any pick this time, and it will drop a different fossils depending on the X, Y, and Z coords.

**Comment by DoubleNegation** [comment]
Supporting this is currently not really viable, sorry.  
This behavior is too complex and non-standard to support in Compact Ores.
