### ISSUE TITLE
Very specific crash

### ISSUE THREAD

**Issue by LlubNek** [DoubleNegation/CompactOres#18]
When mining compact skeleton ore with ore excavator when enigmatic legacy is installed, minecraft crashes.
This is specifically with compact skeleton ore: skeleton ore by itself or other compact ores are fine.

See https://github.com/Extegral/Enigmatic-Legacy/issues/31 for more info.

**Comment by WenXin20** [comment]
Has this issue been fixed yet? I believe I ran into a very similar issue, but I was on a server instead and did not crash, but instead all item entities were immediately being deleted, which is probably worse than a crash and took some digging into the logs to find what was really happening. More information posted at Nukeologist/Sockets#1

**Comment by LlubNek** [comment]
not really fixed, but I made a datapack that'll stop it.
you can find it here: https://github.com/Extegral/Enigmatic-Legacy/issues/31#issuecomment-658728032
I think FunOres is the one to bug about this.

**Comment by WenXin20** [comment]
Thanks! I had already found this and so far it seems to be working. :)

**Comment by DoubleNegation** [comment]
Closing due to fix in Enigmatic Legacy (Extegral/Enigmatic-Legacy@5ad04e94cfb578c40855188933c27cbc3860abf4)
