### ISSUE TITLE
Exception caught during firing event: BIOMES

### ISSUE THREAD

**Issue by Zemogiter** [DoubleNegation/CompactOres#20]
List of mods:
absentbydesign-1.16.2-1.1.0.jar
anviltweaks-3.0.jar
automaticdoors_1.16.2-1.4.jar
balancedenchanting-1.0.jar
bedspreads-forge-1.16.2-5.0.0.0.jar
caelus-forge-1.16.2-2.0.0.0.jar
collective-1.16.2-1.38.jar
compactores-1.16.1-3.0.0.jar
MixinBootstrap-1.0.3.jar

[minecraft crash log.txt](https://github.com/DoubleNegation/CompactOres/files/5102329/minecraft.crash.log.txt)
The issue happens right after splash screen.

**Comment by DoubleNegation** [comment]
This issue is due to the world gen changes in 1.16.2.  
Due to it, Compact Ores 3.0.0 only works in 1.16.1.  
I'll be updating to 1.16.2 soon, I just need to figure out how world gen works now.

**Comment by DoubleNegation** [comment]
I just published version 3.0.1 for Minecraft 1.16.3, which does not suffer from this issue anymore. You can upgrade to that version and Minecraft 1.16.3.
