### ISSUE TITLE
Request-issue on new curse launcher

### ISSUE THREAD

**Issue by IchigoGames** [DoubleNegation/CompactOres#24]
Cant use compactores-1.16.3-3.0.2 on new curse launcher wont download or let me add it to pack due to it being in apha iv had it for a few months now and iv not had any issue with it anyway you could update it to beta even if you dont change anything other then the version numbers like 1.6.3-30.3 beta

**Comment by IchigoGames** [comment]
i realised what i said may sound like a contradiction i have to rebuild my pack due to curse launcher not accept mods from twitch launcher so iv re downloaded everything but ran into a few issues like downloading this mod

**Comment by DoubleNegation** [comment]
Sorry for the inconvenience and for having you wait for so long. I initially wanted to release a beta not too long after the alphas, but I had to take a break from modding for a few months. There's now a beta, with a release version hopefully following in around a week: https://www.curseforge.com/minecraft/mc-mods/compact-ores/files/3284594

**Comment by IchigoGames** [comment]
hm still not showing up on curse launcher mabey it will in a few more hours i tried downloading it and adding it my self but then it wont included it in update

**Comment by IchigoGames** [comment]
oh nvm it looks like it might be a curse issue well hopefully its fixed by tommrow when i update
