### ISSUE TITLE
Compact animated ores don't use the mcmeta file

### ISSUE THREAD

**Issue by WenXin20** [DoubleNegation/CompactOres#25]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Compact Ores v3.0.2`

This is the Gobber2 compact nether ore.
![2020-12-21_18 21 21](https://user-images.githubusercontent.com/12000593/102834342-66f0cd00-43b9-11eb-9912-e57968ea63de.png)

**Comment by DoubleNegation** [comment]
Sorry for the long wait! This is fixed in version 3.0.3 which was just released: https://www.curseforge.com/minecraft/mc-mods/compact-ores/files/3284594

**Comment by WenXin20** [comment]
Thanks!
