### ISSUE TITLE
[1.16.4] Incompatibility with Vanilla Hammers [Forge] mod

### ISSUE THREAD

**Issue by HenryMaxler** [DoubleNegation/CompactOres#26]
When you use the hammer to break a Compact Ore, it breaks only 1 of them instead of any other ore where it breaks 3x3. If you use it on the rock or ore next to it, it will skip breaking the compact ore but break all the ores and stone besides it in a 3x3 area though the harvest level is OK.

[Vanilla Hammers [Forge]](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers-forge)

**Comment by MelanX** [comment]
If you'd release a new version with this commit, it would work: https://github.com/DoubleNegation/CompactOres/commit/f1903acb3968e361636ccf9b276a2c353694719d

**Comment by DoubleNegation** [comment]
>If you'd release a new version with this commit, it would work: f1903ac

Sorry for the long wait! I just released a new version which contains this fix: https://www.curseforge.com/minecraft/mc-mods/compact-ores/files/3284594
