### ISSUE TITLE
Resource packs incompatible

### ISSUE THREAD

**Issue by CarlucciMods** [DoubleNegation/CompactOres#4]
Anyway you can tell me how to correct this.....

1.14.4
forge 28.1.111

**Comment by CarlucciMods** [comment]
Update seems when i remove Modern Arch Resource Pack, its working.....do your mod not play nice with this pack

**Comment by DoubleNegation** [comment]
Resource packs are currently not actively supported by Compact Ores (yet), although some may work. The [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/compact-ores) details under which circumstances they work and under which they don't. In the case of Modern Arch, the resource pack includes textures for the stone but not for the ore itself, which unfortunately makes it incompatible.

**Comment by DoubleNegation** [comment]
The new resource pack support which will be included in the 1.2.0 version still isn't perfect but it's a good step up from what was there previously. The quality of the resulting textures still heavily depends on the details of the resource pack.
