### ISSUE TITLE
Leaves on trees despawn on server

### ISSUE THREAD

**Issue by darkphan** [DoubleNegation/CompactOres#7]
Compact Ores version: 1.14.4-1.2.1.jar
Forge: 28.2.0

It appears that something in the mod is causing leaves to despawn when playing on servers. This did not happen with version 1.1.2. I have validated that it does happen in 1.2.0 and 1.2.1.

**Comment by DoubleNegation** [comment]
While debugging this, I encountered two other bugs that only happen on the dedicated server and fixed them in 9914b81dc5b24ff0d2a571f432c242c94593d16b and ea78f157115e3d00e67af5015f593cb3671ae5ea. One of these two fixes must have fixed the leaf decaying as well, because it isn't happening anymore.
