### ISSUE TITLE
[1.15.2] Mekanism Tin Ore, bug?

### ISSUE THREAD

**Issue by curlywaffles** [DoubleNegation/CompactOres#8]
Adding in ores from Mekanism. Everything seems to be fine except the tin ore texture.

![image](https://user-images.githubusercontent.com/58758245/78503215-d723c980-772a-11ea-91f9-2d1d9daf6de0.png)

![image](https://user-images.githubusercontent.com/58758245/78503226-f4f12e80-772a-11ea-8b5d-731858fa3638.png)

**Comment by curlywaffles** [comment]
Seems to be some kind of issue with the texture being grey scale. I used a resource pack to change the texture of tin ore and it works fine..

**Comment by DoubleNegation** [comment]
It is indeed a problem with the texture being greyscale. For some reason, java ImageIO doesn't handle that properly. (https://stackoverflow.com/questions/31312645/java-imageio-grayscale-png-issue)  
I'll try to find a workaround for that behavior.
