### ISSUE TITLE
Compat w/ The Midnight

### ISSUE THREAD

**Issue by WenXin20** [DoubleNegation/CompactOres#9]
Could default support be added for The Midnight for 1.15.2? 

There are 5 ores in total. I would do it manually, but three of the ores, Tenebrum, Nagrilite, and Dark Pearl, did not have textures created properly. 
It's probably because the ore texture is too similar to it's base stone texture, Nightstone.

Thanks!

**Comment by DoubleNegation** [comment]
[There is actually support already!](https://github.com/DoubleNegation/CompactOres/blob/1.15/src/main/resources/assets/compactores/default_config/definitions/midnight.toml) <sub>(unless I messed up and the file doesn't export properly, please tell me if that's the case)</sub> It was added in the 2.1.0 update, so if you played with 2.0.0, you will have to update and generate new configs.

The similar textures are not really problems, they are what the `maxOreLayerColorDiff` option exists for.

**Comment by WenXin20** [comment]
Alright, thanks!
